export const columns = [
  {
    key: "schedule_id",
    label: "Id",
  },
  {
    key: "user_name",
    label: "Name",
  },
  {
    key: "department_name",
    label: "Department",
  },
  {
    key: "shift",
    label: "Shift",
  },
  {
    key: "phone_number",
    label: "Phone Number",
  },
  {
    key: "created_at",
    label: "Created at",
  },
  {
    key: "action",
    label: "action",
  },

];
export const users = [
  {
    id: 1,
    name: "Mark Dsuza",
    email: "markdsuza@gmail.com",
    project: "designing",
    age: 25,
    point: 8.03,
  },
  {
    id: 2,
    name: "Josef Jennyfer",
    email: "josefjennyfer@gmail.com",
    project: "marketting",
    age: 19,
    point: 7.12,
    nested: [
      {
        id: "I",
        project_name: "UX/UI Design",
        topic: "Full course",
        days: "32 days ago",
      },
      {
        id: "II",
        project_name: "Laravel Development",
        topic: "1/2 Course Point",
        days: "23 days ago",
      },
      {
        id: "III",
        project_name: "Frontend Development",
        topic: "Full Course",
        days: "29 days ago",
      },
    ],
  },
  {
    id: 3,
    name: "Romeo D custa",
    email: "romeodcusta@gmail.com",
    project: "marketting",
    age: 32,
    point: 9.0,
  },
  {
    id: 4,
    name: "Anald Donald",
    email: "analddonald@gmail.com",
    project: "development",
    age: 24,
    point: 9.39,
  },
  {
    id: 5,
    name: "Vicky Patel",
    email: "vickypatel@gamil.com",
    project: "marketting",
    age: 45,
    point: 7.45,
  },
  {
    id: 6,
    name: "John Doe",
    email: "johndoe50@gamil.com",
    project: "designing",
    age: 25,
    point: 8.45,
  },
  {
    id: 7,
    name: "Anald Donald",
    email: "analddonald@gmail.com",
    project: "development",
    age: 24,
    point: 9.39,
  },
  {
    id: 8,
    name: "Vicky Patel",
    email: "vickypatel@gamil.com",
    project: "marketting",
    age: 45,
    point: 7.45,
  },
  {
    id: 9,
    name: "John Doe",
    email: "johndoe50@gamil.com",
    project: "designing",
    age: 25,
    point: 8.45,
  },
  {
    id: 10,
    name: "Anald Donald",
    email: "analddonald@gmail.com",
    project: "development",
    age: 24,
    point: 9.39,
  },
  {
    id: 11,
    name: "Vicky Patel",
    email: "vickypatel@gamil.com",
    project: "marketting",
    age: 45,
    point: 7.45,
  },
  {
    id: 12,
    name: "John Doe",
    email: "johndoe50@gamil.com",
    project: "designing",
    age: 25,
    point: 8.45,
  },
];
